trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'  # You can choose the appropriate agent image

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3'  # Use the desired Python version

  - script: |
      git clone https://github.com/ruifilipetmota/WebGoat
    displayName: 'Clone WebGoat repository'
