trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'  # You can choose the appropriate agent image

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3'  # Use the desired Python version

- script: |
    git clone https://github.com/ruifilipetmota/webgoat.git
  displayName: 'Clone WebGoat repository'

- script: |
    sudo apt update
    sudo apt install -y openjdk-17-jdk
    tar -xzvf zulu17.28.13-ca-jdk17.0.0-linux_amd64.tar.gz -C /usr/lib/jvm
    sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
    java -version
  displayName: 'Install Java 17'

- script: |
    cd webgoat
    # Build and compile your WebGoat project using Apache Maven
    mvn clean compile -f "pom.xml"
  displayName: 'Build and Compile WebGoat with Maven'

- script: |
    # Install PMD
    wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.22.0/pmd-bin-6.22.0.zip
    unzip pmd-bin-6.22.0.zip

    # Run PMD analysis
    ./pmd-bin-6.22.0/bin/run.sh pmd -d src/main/java -f text -R rulesets/java/quickstart.xml
  displayName: 'Run PMD analysis'
