trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'  # Use the "ubuntu-latest" agent image

jobs:
- job: 'BuildWebGoat'
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Use the desired Python version

  - script: |
      # Build the Docker image from the provided Dockerfile
      docker build -t webgoat-builder -f Dockerfile .
    displayName: 'Build Docker Image'

  - script: |
      # Run the build process inside the Docker container
      docker run --rm -v $(Build.SourcesDirectory):/app webgoat-builder
    displayName: 'Build and Compile WebGoat in Docker Container'

  - script: |
      # Install PMD
      wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.22.0/pmd-bin-6.22.0.zip
      unzip pmd-bin-6.22.0.zip

      # Run PMD analysis
      ./pmd-bin-6.22.0/bin/run.sh pmd -d src/main/java -f text -R rulesets/java/quickstart.xml
    displayName: 'Run PMD analysis'