trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: GitHubActions@0
  inputs:
    connectionName: 'ruifilipetmota.WebGoat'
    repositoryName: 'WebGoat'
    workflowName: 'build.yml'