trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'  # You can choose the appropriate agent image

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3'  # Use the desired Python version

- script: |
    git clone https://github.com/ruifilipetmota/webgoat.git
  displayName: 'Clone WebGoat repository'

- script: |
    sudo apt update
    sudo apt install -y openjdk-17-jdk

- script: |
    cd webgoat
    # Build and compile your WebGoat project using Apache Maven
    mvn clean install
  displayName: 'Build and Compile WebGoat with Maven'

- script: |
    # Install PMD
    wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.22.0/pmd-bin-6.22.0.zip
    unzip pmd-bin-6.22.0.zip

    # Run PMD analysis
    ./pmd-bin-6.22.0/bin/run.sh pmd -d src/main/java -f text -R rulesets/java/quickstart.xml
  displayName: 'Run PMD analysis'

