name: Web Goat workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # You can change this to the Java version you need

    - name: Build with Maven
      run: |
        mvn clean install

    - name: Run tests
      run: |
        mvn test